include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Demo loyiha uchun qulayroq bo'lgan yengil sozlamalar
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    use_super_parameters: false
    library_private_types_in_public_api: false
    avoid_print: false
