import '../models/product.dart';

/// Ilova birinchi marta ochilganda yaratiladigan demo mahsulotlar.
/// Barcha nom va tavsiflar o'zbek tilida.
class SeedData {
  SeedData._();

  static List<Product> products() => [
        // ============ TELEFONLAR ============
        Product(
          id: 'p01',
          name: 'Nova X10',
          category: 'Telefonlar',
          price: 2499000,
          oldPrice: 2999000,
          description:
              'Nova X10 — zamonaviy dizayn va kuchli batareya. 6.7 dyuymli AMOLED ekran, 128 GB xotira va 50 MP kamera bilan kun bo\'yi ishonchli hamrohingiz.',
          image: 'assets/products/p01.jpg',
          rating: 4.7,
          stock: 24,
          isNew: true,
          isPopular: true,
          features: [
            '6.7" AMOLED ekran, 120 Gts',
            '50 MP asosiy kamera',
            '128 GB xotira, 8 GB RAM',
            '5000 mA·soat batareya',
            'Tez zaryadlash 33 Vt',
          ],
        ),
        Product(
          id: 'p02',
          name: 'UltraPhone 24 Pro',
          category: 'Telefonlar',
          price: 4599000,
          oldPrice: 5199000,
          description:
              'Flagship UltraPhone 24 Pro — titan korpus, uch kamera tizimi va 6.8 dyuymli LTPO ekran. Video va fotografiya uchun eng yaxshi tanlov.',
          image: 'assets/products/p02.jpg',
          rating: 4.9,
          stock: 12,
          isPopular: true,
          features: [
            '6.8" LTPO OLED ekran, 120 Gts',
            'Titan korpus',
            'Uch kamera: 50+50+12 MP',
            '256 GB xotira, 12 GB RAM',
            '5000 mA·soat batareya',
          ],
        ),
        Product(
          id: 'p03',
          name: 'MaxPhone 15',
          category: 'Telefonlar',
          price: 3199000,
          oldPrice: 3599000,
          description:
              'MaxPhone 15 — oqlangan dizayn, yorqin ekran va ajoyib kamera. Kundalik ishlar, ijtimoiy tarmoqlar va suratlar uchun ideal.',
          image: 'assets/products/p03.jpg',
          rating: 4.6,
          stock: 30,
          features: [
            '6.5" Super Retina ekran',
            '48 MP kamera',
            '128 GB xotira, 8 GB RAM',
            '4000 mA·soat batareya',
            'IP68 suv o\'tkazmaydigan',
          ],
        ),
        Product(
          id: 'p04',
          name: 'Techno X200',
          category: 'Telefonlar',
          price: 1799000,
          oldPrice: 2099000,
          description:
              'Techno X200 — arzon va ishonchli. Katta ekran, kuchli batareya va zamonaviy dizayn — o\'quvchilar va katta oilalar uchun ajoyib tanlov.',
          image: 'assets/products/p04.jpg',
          rating: 4.3,
          stock: 45,
          isNew: true,
          features: [
            '6.6" LCD ekran, 90 Gts',
            'Dual kamera 50+2 MP',
            '64 GB xotira, 4 GB RAM',
            '6000 mA·soat batareya',
            'Ikki SIM',
          ],
        ),

        // ============ KOMPYUTERLAR ============
        Product(
          id: 'p05',
          name: 'UltraPC Office',
          category: 'Kompyuterlar',
          price: 3899000,
          oldPrice: 4299000,
          description:
              'UltraPC Office — ofis va o\'qish uchun tayyor kompyuter. Intel Core i5, 16 GB RAM va SSD xotira bilan barcha dasturlar tez ishlaydi.',
          image: 'assets/products/p05.jpg',
          rating: 4.5,
          stock: 8,
          features: [
            'Intel Core i5-12400',
            '16 GB DDR4 RAM',
            '512 GB SSD',
            'Uyasi: monitor, klaviatura, sichqoncha',
            '1 yil kafolat',
          ],
        ),
        Product(
          id: 'p06',
          name: 'GamerX RTX',
          category: 'Kompyuterlar',
          price: 8999000,
          oldPrice: 10499000,
          description:
              'GamerX RTX — eng talabchan o\'yinlar uchun mo\'ljallangan kompyuter. NVIDIA RTX grafikasi, RGB yoritish va shisha panel bilan ajoyib ko\'rinish.',
          image: 'assets/products/p06.jpg',
          rating: 4.8,
          stock: 5,
          isPopular: true,
          features: [
            'Intel Core i7-13700',
            'NVIDIA RTX 4060 8 GB',
            '32 GB DDR5 RAM',
            '1 TB NVMe SSD',
            'RGB yoritish, shisha panel',
          ],
        ),
        Product(
          id: 'p07',
          name: 'Monitor LED 27"',
          category: 'Kompyuterlar',
          price: 1899000,
          oldPrice: 2199000,
          description:
              '27 dyuymli Full HD monitor — yupqa ramka, 75 Gts chastota va ko\'z himoyasi rejimi. Ishlash va o\'yin uchun ham mos.',
          image: 'assets/products/p07.jpg',
          rating: 4.4,
          stock: 16,
          features: [
            '27" IPS, Full HD (1920×1080)',
            '75 Gts chastota',
            'HDMI va VGA uyalari',
            'Ko\'z himoyasi rejimi',
            'Yupqa ramka dizayni',
          ],
        ),

        // ============ NOUTBUKLAR ============
        Product(
          id: 'p08',
          name: 'AirBook 14',
          category: 'Noutbuklar',
          price: 4199000,
          oldPrice: 4799000,
          description:
              'AirBook 14 — yengil (1.3 kg) va nozik noutbuk. Kuchli batareya 15 soatgacha ishlaydi, metall korpus zamonaviy ko\'rinish beradi.',
          image: 'assets/products/p08.jpg',
          rating: 4.7,
          stock: 14,
          isNew: true,
          isPopular: true,
          features: [
            '14" Retina ekran',
            'Apple M2 chip / Intel i5',
            '8 GB RAM, 256 GB SSD',
            '15 soatgacha batareya',
            '1.3 kg og\'irlik',
          ],
        ),
        Product(
          id: 'p09',
          name: 'ProBook 15',
          category: 'Noutbuklar',
          price: 3499000,
          oldPrice: 3999000,
          description:
              'ProBook 15 — biznes uchun ishonchli noutbuk. Katta ekran, qulay klaviatura va himoyalangan ma\'lumotlar saqlash tizimi.',
          image: 'assets/products/p09.jpg',
          rating: 4.5,
          stock: 11,
          features: [
            '15.6" Full HD ekran',
            'Intel Core i5-1235U',
            '16 GB RAM, 512 GB SSD',
            'Orqa yoritilgan klaviatura',
            '8 soatgacha batareya',
          ],
        ),
        Product(
          id: 'p10',
          name: 'GamerBook 16',
          category: 'Noutbuklar',
          price: 7499000,
          oldPrice: 8499000,
          description:
              'GamerBook 16 — 165 Gts ekran va RTX grafikasi bilan o\'yinlar yangi darajada. RGB klaviatura va kuchli sovutish tizimi.',
          image: 'assets/products/p10.jpg',
          rating: 4.8,
          stock: 6,
          isPopular: true,
          features: [
            '16" QHD ekran, 165 Gts',
            'NVIDIA RTX 4070 8 GB',
            '32 GB RAM, 1 TB SSD',
            'RGB klaviatura',
            'Kuchli sovutish tizimi',
          ],
        ),

        // ============ PLANSHETLAR ============
        Product(
          id: 'p11',
          name: 'Tab Pro 11',
          category: 'Planshetlar',
          price: 2999000,
          oldPrice: 3499000,
          description:
              'Tab Pro 11 — katta va yorqin ekranli planshet. Stilus qalam bilan chizish va yozish uchun mo\'ljallangan, o\'qish va kino uchun ideal.',
          image: 'assets/products/p11.jpg',
          rating: 4.6,
          stock: 18,
          isNew: true,
          features: [
            '11" 2K ekran, 120 Gts',
            'Stilus qalam qo\'llab-quvvatlaydi',
            '8 GB RAM, 128 GB xotira',
            'Katta dinamiklar',
            '8000 mA·soat batareya',
          ],
        ),
        Product(
          id: 'p12',
          name: 'Tab Lite 8',
          category: 'Planshetlar',
          price: 1299000,
          oldPrice: 1499000,
          description:
              'Tab Lite 8 — ixcham va yengil planshet. Bolalar uchun ta\'lim ilovalari va katta yoshdagilar uchun qulay o\'qish qurilmasi.',
          image: 'assets/products/p12.jpg',
          rating: 4.2,
          stock: 27,
          features: [
            '8" HD ekran',
            '4 GB RAM, 64 GB xotira',
            'Yengil — 320 gramm',
            'Bolalar rejimi mavjud',
            '5000 mA·soat batareya',
          ],
        ),

        // ============ TELEVIZORLAR ============
        Product(
          id: 'p13',
          name: 'Smart TV 55" 4K',
          category: 'Televizorlar',
          price: 6499000,
          oldPrice: 7499000,
          description:
              '55 dyuymli 4K Smart TV — HDR10+ va Dolby Vision bilan filmlar jonlanadi. O\'rnatilgan Wi-Fi va aqlli televidenie tizimi.',
          image: 'assets/products/p13.jpg',
          rating: 4.8,
          stock: 7,
          isPopular: true,
          features: [
            '55" 4K UHD ekran',
            'HDR10+ va Dolby Vision',
            'Smart TV (Android TV)',
            'O\'rnatilgan Wi-Fi',
            '3× HDMI, 2× USB',
          ],
        ),
        Product(
          id: 'p14',
          name: 'Televizor 43" Full HD',
          category: 'Televizorlar',
          price: 3299000,
          oldPrice: 3799000,
          description:
              '43 dyuymli Full HD televizor — yorqin ranglar va aniq tasvir. Kichik va o\'rta xonalar uchun ajoyib tanlov.',
          image: 'assets/products/p14.jpg',
          rating: 4.4,
          stock: 10,
          features: [
            '43" Full HD ekran',
            '60 Gts chastota',
            '2× HDMI, 2× USB',
            'Yengil va yupqa dizayn',
            'Devor uchun moslama ichida',
          ],
        ),

        // ============ QULOQCHINLAR ============
        Product(
          id: 'p15',
          name: 'AirBuds Pro',
          category: 'Quloqchinlar',
          price: 899000,
          oldPrice: 1199000,
          description:
              'AirBuds Pro — aktiv shovqin o\'chirish (ANC) funksiyali simsiz quloqchinlar. 30 soatgacha ishlash va suvga chidamlilik.',
          image: 'assets/products/p15.jpg',
          rating: 4.7,
          stock: 40,
          isNew: true,
          isPopular: true,
          features: [
            'Aktiv shovqin o\'chirish (ANC)',
            '30 soatgacha batareya',
            'Bluetooth 5.3',
            'Suvga chidamli (IPX5)',
            'Sensorli boshqaruv',
          ],
        ),
        Product(
          id: 'p16',
          name: 'AirBuds Lite',
          category: 'Quloqchinlar',
          price: 499000,
          oldPrice: 699000,
          description:
              'AirBuds Lite — arzon va sifatli simsiz quloqchinlar. Sport va kundalik foydalanish uchun qulay, yaxshi ovoz sifati.',
          image: 'assets/products/p16.jpg',
          rating: 4.4,
          stock: 55,
          features: [
            'Bluetooth 5.2',
            '24 soatgacha batareya',
            'Mikrofonli',
            'Yengil — 4 gramm',
            'USB-C zaryadlash',
          ],
        ),
        Product(
          id: 'p17',
          name: 'MaxSound',
          category: 'Quloqchinlar',
          price: 1499000,
          oldPrice: 1899000,
          description:
              'MaxSound — quloq ustki naushnik. Chuqur bass, yumshoq yostiqchalar va 40 soatgacha ishlash muddati.',
          image: 'assets/products/p17.jpg',
          rating: 4.6,
          stock: 22,
          features: [
            'Quloq ustki (over-ear)',
            '40 soatgacha batareya',
            'Chuqur bass ovoz',
            'Yumshoq yostiqchalar',
            'Buklanadigan dizayn',
          ],
        ),

        // ============ AKSESSUARLAR ============
        Product(
          id: 'p18',
          name: 'Watch S9',
          category: 'Aksessuarlar',
          price: 1199000,
          oldPrice: 1499000,
          description:
              'Watch S9 — aqlli soat: yurak urishini kuzatish, sport rejimlari, qo\'ng\'iroqlar va xabarlar. 10 kungacha batareya.',
          image: 'assets/products/p18.jpg',
          rating: 4.5,
          stock: 33,
          isPopular: true,
          features: [
            '1.9" AMOLED ekran',
            'Yurak urishini kuzatish',
            '100+ sport rejimi',
            'GPS',
            '10 kungacha batareya',
          ],
        ),
        Product(
          id: 'p19',
          name: 'PowerBank 20000 mA·soat',
          category: 'Aksessuarlar',
          price: 399000,
          oldPrice: 499000,
          description:
              '20000 mA·soat quvvat banki — telefoningizni 4-5 marta to\'liq zaryadlaydi. Ikki USB chiqishi bilan birdaniga ikkita qurilma.',
          image: 'assets/products/p19.jpg',
          rating: 4.6,
          stock: 48,
          features: [
            '20000 mA·soat sig\'im',
            'Ikki USB chiqish',
            'Tez zaryadlash 22.5 Vt',
            'LED ko\'rsatkich',
            'Yengil va ixcham',
          ],
        ),
        Product(
          id: 'p20',
          name: 'Kabel USB-C 2 m',
          category: 'Aksessuarlar',
          price: 89000,
          oldPrice: 119000,
          description:
              'Uzunlik 2 metr bo\'lgan mustahkam USB-C kabel. Tez zaryadlash va ma\'lumot uzatishni qo\'llab-quvvatlaydi.',
          image: 'assets/products/p20.jpg',
          rating: 4.3,
          stock: 120,
          features: [
            'Uzunligi 2 metr',
            '60 Vt tez zaryadlash',
            'Ma\'lumot uzatish',
            'Mustahkam to\'qima',
            'To\'qimagan plastik',
          ],
        ),

        // ============ KIYIM-KECHAK ============
        Product(
          id: 'p21',
          name: 'Futbolka Premium (oq)',
          category: 'Kiyim-kechak',
          price: 129000,
          oldPrice: 159000,
          description:
              '100% paxtadan tayyorlangan oq futbolka. Yumshoq mato, nafas oladigan va yuvilganda formasi buzilmaydi.',
          image: 'assets/products/p21.jpg',
          rating: 4.5,
          stock: 80,
          features: [
            '100% paxta',
            'O\'lchamlar: S–XXL',
            'Yuvilganda buzilmaydi',
            'Nafas oladigan mato',
            'Erkaklar va ayollar uchun',
          ],
        ),
        Product(
          id: 'p22',
          name: "Ko'ylak Elegant",
          category: 'Kiyim-kechak',
          price: 349000,
          oldPrice: 429000,
          description:
              'Elegant ko\'ylak — bayram va maxsus tadbirlar uchun. Oqilona kesim, yuqori sifatli mato, qulay kiyiladi.',
          image: 'assets/products/p22.jpg',
          rating: 4.6,
          stock: 25,
          isNew: true,
          features: [
            'Yuqori sifatli mato',
            'O\'lchamlar: S–XL',
            'Bayram uchun dizayn',
            'Dazmollash oson',
            'Yumshoq astar',
          ],
        ),
        Product(
          id: 'p23',
          name: 'Kurtka Qishki',
          category: 'Kiyim-kechak',
          price: 799000,
          oldPrice: 949000,
          description:
              'Issiq qishki kurtka — shamol va sovuqdan himoya. Kapyushon, ko\'p cho\'ntaklar va suv o\'tkazmaydigan mato.',
          image: 'assets/products/p23.jpg',
          rating: 4.7,
          stock: 19,
          isPopular: true,
          features: [
            'Suv o\'tkazmaydigan mato',
            'Issiq astar (-15°C gacha)',
            'Kapyushon',
            '6 ta cho\'ntak',
            'O\'lchamlar: M–XXL',
          ],
        ),

        // ============ OYOQ KIYIMLAR ============
        Product(
          id: 'p24',
          name: 'Krossovkalar SportMax',
          category: 'Oyoq kiyimlar',
          price: 649000,
          oldPrice: 799000,
          description:
              'SportMax krossovkalari — yugurish va kundalik foydalanish uchun. Yengil taglik, nafas oladigan ustki qism.',
          image: 'assets/products/p24.jpg',
          rating: 4.5,
          stock: 35,
          features: [
            'Yengil va elastik taglik',
            'Nafas oladigan mato',
            'O\'lchamlar: 38–45',
            'Sport va shahar uchun',
            'Yuvish mumkin',
          ],
        ),
        Product(
          id: 'p25',
          name: 'Tufli Klassik',
          category: 'Oyoq kiyimlar',
          price: 549000,
          oldPrice: 649000,
          description:
              'Klassik erkaklar tuflisi — ish uchrashuvlari va rasmiy tadbirlar uchun. Haqiqiy charmdan, qulay taglik.',
          image: 'assets/products/p25.jpg',
          rating: 4.4,
          stock: 17,
          features: [
            'Haqiqiy charm',
            'O\'lchamlar: 39–45',
            'Qulay ortopedik taglik',
            'Rasmiy tadbirlar uchun',
            'Uzoq muddat xizmat qiladi',
          ],
        ),

        // ============ MAISHIY TEXNIKA ============
        Product(
          id: 'p26',
          name: 'Kir yuvish mashinasi AquaClean',
          category: 'Maishiy texnika',
          price: 5499000,
          oldPrice: 6299000,
          description:
              'AquaClean — 8 kg yuk ko\'taradigan avtomatik kir yuvish mashinasi. 16 dastur, bug\' bilan tozalash va past shovqin darajasi.',
          image: 'assets/products/p26.jpg',
          rating: 4.7,
          stock: 6,
          isPopular: true,
          features: [
            '8 kg yuk',
            '16 yuvish dasturi',
            'Bug\' bilan tozalash',
            'Past shovqin (52 dB)',
            'Energiya sinfi A+++',
          ],
        ),
        Product(
          id: 'p27',
          name: 'Sovutgich CoolFrost 350',
          category: 'Maishiy texnika',
          price: 4999000,
          oldPrice: 5799000,
          description:
              'CoolFrost 350 — 350 litrli ikki kamerali sovutgich. No Frost tizimi muzlashni oldini oladi, energiya tejamkor.',
          image: 'assets/products/p27.jpg',
          rating: 4.6,
          stock: 5,
          features: [
            '350 litr hajm',
            'No Frost tizimi',
            'Past energiya sarfi',
            'Ichki yoritish',
            'O\'lchamlari: 60×66×190 sm',
          ],
        ),
        Product(
          id: 'p28',
          name: 'Mikroto\'lqinli pech MicroWave 20L',
          category: 'Maishiy texnika',
          price: 1099000,
          oldPrice: 1349000,
          description:
              '20 litrli mikroto\'lqinli pech — 800 Vt quvvat, 8 ta dastur va taymer. Ovqatni tez va bir tekis isitadi.',
          image: 'assets/products/p28.jpg',
          rating: 4.4,
          stock: 15,
          features: [
            '20 litr hajm',
            '800 Vt quvvat',
            '8 ta avtomatik dastur',
            'Taymer va signal',
            'Yengil — 11 kg',
          ],
        ),
        Product(
          id: 'p29',
          name: 'Elektr choynak TeaLux',
          category: 'Maishiy texnika',
          price: 299000,
          oldPrice: 369000,
          description:
              'TeaLux — 1.7 litrli elektr choynak. 2200 Vt quvvat bilan 3-4 daqiqada qaynaydi. Avtomatik o\'chish xavfsizligi.',
          image: 'assets/products/p29.jpg',
          rating: 4.5,
          stock: 60,
          features: [
            '1.7 litr hajm',
            '2200 Vt quvvat',
            'Zanglamaydigan po\'lat',
            'Avtomatik o\'chish',
            '360° aylanuvchi taglik',
          ],
        ),

        // ============ UY UCHUN ============
        Product(
          id: 'p30',
          name: 'Divan Modern 3 o\'rinli',
          category: 'Uy uchun',
          price: 2799000,
          oldPrice: 3299000,
          description:
              'Modern divan — zamonaviy yashash xonasi uchun. Qulay o\'rindiq, yumshoq yostiqlar va mustahkam rama.',
          image: 'assets/products/p30.jpg',
          rating: 4.6,
          stock: 4,
          features: [
            '3 o\'rinli',
            'Yumshoq yostiqlar',
            'Mustahkam yog\'och rama',
            'Tozalash oson mato',
            'O\'lchamlari: 210×90×85 sm',
          ],
        ),
        Product(
          id: 'p31',
          name: 'Oshxona to\'plami (stol + 4 stul)',
          category: 'Uy uchun',
          price: 1899000,
          oldPrice: 2299000,
          description:
              'Oshxona to\'plami — katta stol va 4 ta qulay stul. Oila bilan ovqatlanish va mehmonlar uchun yetarli joy.',
          image: 'assets/products/p31.jpg',
          rating: 4.3,
          stock: 9,
          features: [
            'Stol + 4 stul',
            'Yog\'och va metall',
            'Oson yig\'iladi',
            'Tozalash oson',
            'Stol: 120×70 sm',
          ],
        ),
        Product(
          id: 'p32',
          name: 'Robot changyutgich RobotVac',
          category: 'Uy uchun',
          price: 1699000,
          oldPrice: 2199000,
          description:
              'RobotVac — aqlli robot changyutgich. Xaritani tuzadi, avtomatik zaryadlanadi va hatto gilam ustida ham tozalaydi.',
          image: 'assets/products/p32.jpg',
          rating: 4.5,
          stock: 12,
          isNew: true,
          features: [
            'Aqlli xarita tuzish',
            'Avtomatik zaryadlash',
            'Ho\'l tozalash funksiyasi',
            'Telefon orqali boshqaruv',
            'Past balandlik (8 sm)',
          ],
        ),

        // ============ GO'ZALLIK ============
        Product(
          id: 'p33',
          name: 'Parfyum Royal Oud',
          category: "Go'zallik",
          price: 899000,
          oldPrice: 1099000,
          description:
              'Royal Oud — hashamatli sharqona parfyum. Oud, amber va sandal daraxti notalari bilan uzoq muddat saqlanadigan hid.',
          image: 'assets/products/p33.jpg',
          rating: 4.8,
          stock: 28,
          isPopular: true,
          features: [
            '50 ml hajm',
            'Sharqona oud notalari',
            '8+ soat saqlanadi',
            'Erkaklar va ayollar uchun',
            'Premium qadoqlash',
          ],
        ),
        Product(
          id: 'p34',
          name: 'DermiCare parvarish to\'plami',
          category: "Go'zallik",
          price: 349000,
          oldPrice: 449000,
          description:
              'DermiCare — terini parvarish qilish to\'plami: tozalash, namlash va himoya. Tabiiy tarkib, barcha teri turlari uchun.',
          image: 'assets/products/p34.jpg',
          rating: 4.5,
          stock: 40,
          features: [
            '3 bosqichli parvarish',
            'Tabiiy tarkib',
            'Barcha teri turlari uchun',
            'Parabenlarsiz',
            '2 oyga yetadi',
          ],
        ),
        Product(
          id: 'p35',
          name: 'Soch fen quritgich AirHype',
          category: "Go'zallik",
          price: 749000,
          oldPrice: 949000,
          description:
              'AirHype — professional fen. 1600 Vt quvvat, 3 tezlik rejimi va sovuq havo funksiyasi bilan sochlarni tez va xavfsiz quritadi.',
          image: 'assets/products/p35.jpg',
          rating: 4.6,
          stock: 21,
          features: [
            '1600 Vt quvvat',
            '3 tezlik + sovuq havo',
            '2 ta nozul',
            'Yengil vazn',
            'Ion texnologiyasi',
          ],
        ),

        // ============ SPORT ============
        Product(
          id: 'p36',
          name: 'Gantel to\'plami 2×5 kg',
          category: 'Sport',
          price: 599000,
          oldPrice: 749000,
          description:
              'Ikkita 5 kg\'lik gantel — uyda mashq qilish uchun. Anti-skid qoplamali, qulay ushlash.',
          image: 'assets/products/p36.jpg',
          rating: 4.5,
          stock: 32,
          features: [
            '2×5 kg',
            'Anti-skid qoplama',
            'Uyda mashq uchun',
            'Mustahkam material',
            'Qulay ushlash',
          ],
        ),
        Product(
          id: 'p37',
          name: 'Fitnes arqon',
          category: 'Sport',
          price: 99000,
          oldPrice: 129000,
          description:
              'Professional fitnes arqon — kaloriya yoqish va chidamlilikni oshirish uchun. Uzunligi sozlanadi.',
          image: 'assets/products/p37.jpg',
          rating: 4.3,
          stock: 70,
          features: [
            'Uzunligi sozlanadi',
            'Yengil material',
            'Aylanuvchi tutqichlar',
            'Sumka bilan',
            'Barcha bo\'y uchun',
          ],
        ),
        Product(
          id: 'p38',
          name: 'Yoga gilami',
          category: 'Sport',
          price: 149000,
          oldPrice: 199000,
          description:
              'Yoga gilami — sirpanmaydigan, yumshoq va ekologik toza. O\'zi bilan olib yurish uchun qulay.',
          image: 'assets/products/p38.jpg',
          rating: 4.4,
          stock: 45,
          isNew: true,
          features: [
            '183×61 sm',
            'Sirpanmaydigan sirt',
            '6 mm qalinlik',
            'Yengil — 1 kg',
            'Tasma bilan',
          ],
        ),
        Product(
          id: 'p39',
          name: 'Velosiped City 26',
          category: 'Sport',
          price: 2999000,
          oldPrice: 3499000,
          description:
              'City 26 — shahar uchun qulay velosiped. 21 tezlik, orqa yukxalta va yaxshi amortizatsiya tizimi.',
          image: 'assets/products/p39.jpg',
          rating: 4.6,
          stock: 7,
          features: [
            '26" g\'ildiraklar',
            '21 tezlik',
            'Amortizatsiya',
            'Orqa yukxalta',
            'Disk tormozlar',
          ],
        ),

        // ============ BOLALAR ============
        Product(
          id: 'p40',
          name: 'Yumshoq o\'yinchoq Ayiqcha',
          category: 'Bolalar mahsulotlari',
          price: 199000,
          oldPrice: 249000,
          description:
              'Katta yumshoq ayiqcha — bolaning eng yaxshi do\'sti. Gipoallergen material, yuvish mumkin.',
          image: 'assets/products/p40.jpg',
          rating: 4.8,
          stock: 38,
          isPopular: true,
          features: [
            'Balandligi 60 sm',
            'Gipoallergen material',
            'Yuvish mumkin',
            '3 yoshdan katta bolalar',
            'Sifat sertifikati',
          ],
        ),
        Product(
          id: 'p41',
          name: 'Qurilish bloklari (120 dona)',
          category: 'Bolalar mahsulotlari',
          price: 249000,
          oldPrice: 299000,
          description:
              '120 dona rang-barang qurilish bloklari — bola tasavvurini rivojlantiradi. Xavfsiz plastik, sertifikatlangan.',
          image: 'assets/products/p41.jpg',
          rating: 4.7,
          stock: 52,
          features: [
            '120 dona',
            'Xavfsiz plastik',
            '3 yoshdan boshlab',
            'Tasavvurni rivojlantiradi',
            'Yig\'ish oson',
          ],
        ),
        Product(
          id: 'p42',
          name: 'Bolalar velosipedi (14")',
          category: 'Bolalar mahsulotlari',
          price: 799000,
          oldPrice: 949000,
          description:
              '14 dyuymli bolalar velosipedi — 3-5 yoshli bolalar uchun. Yon g\'ildiraklar, savatcha va qo\'ng\'iroq.',
          image: 'assets/products/p42.jpg',
          rating: 4.5,
          stock: 11,
          features: [
            '14" g\'ildiraklar',
            '3-5 yosh uchun',
            'Yon g\'ildiraklar',
            'Savatcha',
            'Qo\'ng\'iroq',
          ],
        ),

        // ============ AVTOMOBIL ============
        Product(
          id: 'p43',
          name: 'Avtomobil telefon ushlagichi',
          category: 'Avtomobil mahsulotlari',
          price: 149000,
          oldPrice: 189000,
          description:
              'Magnetli telefon ushlagichi — haydash paytida telefoningiz xavfsiz joyda. Oson o\'rnatiladi, mustahkam ushlaydi.',
          image: 'assets/products/p43.jpg',
          rating: 4.5,
          stock: 64,
          features: [
            'Magnetli tizim',
            '360° aylanadi',
            'Oson o\'rnatish',
            'Barcha telefonlar uchun',
            'Mustahkam yopishqoq',
          ],
        ),
        Product(
          id: 'p44',
          name: 'DVR videoregistrator',
          category: 'Avtomobil mahsulotlari',
          price: 649000,
          oldPrice: 799000,
          description:
              'DVR videoregistrator — 2K tasvir sifati, tungi ko\'rish va aylanma yozib olish. Yo\'l hodisalarida isbot sifatida xizmat qiladi.',
          image: 'assets/products/p44.jpg',
          rating: 4.6,
          stock: 20,
          isNew: true,
          features: [
            '2K tasvir sifati',
            'Tungi ko\'rish (IR)',
            'Aylanma yozib olish',
            'G-sensor',
            'SD karta 128 GB gacha',
          ],
        ),
      ];
}
